#!/usr/bin/env bash
# PreToolUse guard: Warn when modifying generated files
set -euo pipefail

FILE_PATH="${FILE_PATH:-}"
TOOL_NAME="${TOOL_NAME:-}"

# Only check for edit/write operations
if [[ ! "${TOOL_NAME,,}" =~ ^(edit|write)$ ]]; then
  exit 0
fi

# Skip if no file path
if [[ -z "${FILE_PATH}" ]]; then
  exit 0
fi

# Guard generated HTML/RSS/sitemap - these are auto-generated by the pipeline
if [[ "${FILE_PATH}" =~ ^public/(index\.html|feed\.xml|sitemap\.xml)$ ]]; then
  echo "Warning: Modifying generated file ${FILE_PATH}. This will be overwritten by the pipeline." >&2
fi

# Guard archive files
if [[ "${FILE_PATH}" =~ ^public/archive/ ]]; then
  echo "Warning: Modifying archived content. Archives are managed by the pipeline." >&2
fi

# Guard image cache
if [[ "${FILE_PATH}" =~ ^data/image_cache/ ]]; then
  echo "Warning: Modifying image cache. Cache is managed automatically." >&2
fi

exit 0
